apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: BAU release
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
env:
  PAT: ${{ secrets.PAT }}
  CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
  workflowId: 4de0b3c3-382a-40cf-88e5-f029d6ce194c
jobs:
  setup:
    outputs:
      base-manifest: ${{ steps.manifest.outputs.base-manifest }}
    steps:
      - name: Create manifest from latest artifacts in current org
        id: manifest
        uses: gmaxey/generate-base-manifest
        with:
          workflowId: ${{ env.workflowId }}
  pre-prod:
    steps:
      - name: Update manifest file with environment
        with:
          base-manifest: ${{ needs.setup.outputs.base-manifest }}
          environment: BugleTest
          file: manifest.yaml
        uses: gmaxey/create-manifest-file
      - name: deploy
        uses: cloudbees-io/workflows-dispatch
        with:
          workflows-dispatch-file: manifest.yaml
          token: ${{ secrets.PAT}}
    needs: setup
  SRE:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    needs: pre-prod
    with:
      approvers: ""
      disallowLaunchByUser: false
      instructions: Please approve for production deployment
  prod:
    steps:
      - name: Update manifest file with environment
        with:
          base-manifest: ${{ needs.setup.outputs.base-manifest }}
          environment: BugleProd
          file: manifest.yaml
        uses: gmaxey/create-manifest-file
      - name: deploy
        uses: cloudbees-io/workflows-dispatch
        with:
          workflows-dispatch-file: manifest.yaml
          token: ${{ secrets.PAT}}
    needs:
      - SRE
      - setup
